services:
  backrest:
    image: ghcr.io/msenturk/backrest-docker-volume-backup:latest
    container_name: backrest
    restart: unless-stopped
    privileged: true
    ports:
      - "9898:9898"
    volumes:
      # Persistent configuration and data
      - ./data:/data
      - ./config:/config
      - ./local-backups:/repos
      
      - /home/murat:/home/murat:ro

      # Auto-Discovery Socket & Volume Mounts
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rw

    environment:
      - BACKREST_CONFIG=/config/config.json
      - BACKREST_DATA_DIR=/data
